### PR TITLE
A problem that is not referenced. by nuget.

### PR DESCRIPTION
**Pull request by shchy**

### CODE REVIEW

**Comment by MrMitch** [comment]
Hi @shchy, thank you for your pull-request.
I started doing some un-pushed refactoring and changing the output type to be a class library was already done. I also changed the organisation of the source code.

I published a new version of the package, last version, available on [NuGet](https://www.nuget.org/packages/MrMitch.Loaders/).

Can you tell me if this version fixes your problem ?

**Comment by shchy** [comment]
Thank you. You me to solve my problem.
However, I am in the remaining one, is a problem.
My .NetFramework is v4.5
This v4.5.2
Here there is a difference, it is a result errors.

**Comment by MrMitch** [comment]
v1.2.0 is compatible with .Net 4.5

**Comment by MrMitch** [comment]
Please try to update to the last version of the NuGet package, **v1.2.0**, which supports .NET 4.5.
If VisualStudio has troubles updating the package, I would suggest that you remove it and install it again.
You can find an exemple of a working solution with .NET 4.5 [here](https://www.dropbox.com/s/451vu7e5w07lji5/Loaders45.zip?dl=1)

**Comment by shchy** [comment]
I was able to it.
Thank you.

**Pull request closed without merging**
